-- wbsテーブル作成SQL
-- プロジェクトのWBS行データを格納するテーブル

-- 既存のテーブルを削除（テーブル変更に対応）
DROP TABLE IF EXISTS wbs;

-- wbsテーブルの作成（prisma/schema.mysql.prisma に準拠）
CREATE TABLE wbs (
    ID INT NOT NULL AUTO_INCREMENT,
    FILE_NAME VARCHAR(200) NULL,
    ROW_NO INT NULL,
    PROJECT_ID VARCHAR(50) NULL,
    PROJECT_NAME VARCHAR(200) NULL,
    WBS_ID VARCHAR(30) NULL,
    PHASE VARCHAR(25) NULL,
    ACTIVITY VARCHAR(50) NULL,
    TASK VARCHAR(100) NULL,
    KINO_SBT VARCHAR(20) NULL,
    SUBSYSTEM VARCHAR(50) NULL,
    TANTO VARCHAR(20) NULL,
    TANTO_REV VARCHAR(20) NULL,
    KIJUN_START_DATE DATE NULL,
    KIJUN_END_DATE DATE NULL,
    KIJUN_KOSU FLOAT NULL,
    KIJUN_KOSU_BUFFER FLOAT NULL,
    YOTEI_START_DATE DATE NULL,
    YOTEI_END_DATE DATE NULL,
    YOTEI_KOSU FLOAT NULL,
    JISSEKI_START_DATE DATE NULL,
    JISSEKI_END_DATE DATE NULL,
    JISSEKI_KOSU FLOAT NULL,
    STATUS VARCHAR(20) NULL,
    IPV_DATE DATE NULL,
    IBPV_DATE DATE NULL,
    PV_DATE DATE NULL,
    EV_DATE DATE NULL,
    AC_DATE DATE NULL,
    IPV_KOSU FLOAT NULL,
    IBPV_KOSU FLOAT NULL,
    PV_KOSU FLOAT NULL,
    EV_KOSU FLOAT NULL,
    AC_KOSU FLOAT NULL,
    BIKO TEXT NULL,
    PROGRESS_RATE FLOAT NULL,
    PRIMARY KEY (ID),
    KEY INDEX1 (PROJECT_ID, WBS_ID),
    KEY INDEX2 (PROJECT_ID, PHASE, STATUS)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- テーブル作成完了の確認
SELECT 'wbsテーブルが正常に作成されました' AS result;